### ISSUE TITLE
MTK Meta smart card not detected error

### ISSUE THREAD

**Issue by LeonhardEuler314** [neutronscott/flip2#13]
I am trying to use the MTK Meta application (now called Android Utility), but every time I try to start it it opens a dialogue box telling me to load a valid smart card. I don't really know what a smart card is, but I tried to google and found several videos wherein it works as long as you insert usb stick which I tried to no avail. I downloaded and configured the Microsoft smart card reader driver, and it still did not work. I would remove the code that checks for a smart card but I have no idea where to look for it in the file. Did anyone else experience this problem, and if so how did you resolve it?

**Comment by neutronscott** [comment]
check the wiki for new instruction to use autobooter instead of that
