### ISSUE TITLE
How do i fix No MTK Preloader ports found!

### ISSUE THREAD

**Issue by Cbo11** [neutronscott/flip2#18]
the 3 lines of code are:
Have USB attached and then remove/insert battery.
Searching registry for MTK Preloader ports.
No MTK Preloader ports found!
also, im pretty confused on the reboot part, and then you put in the file path to autobooter.exe? any help would be useful!

**Comment by neutronscott** [comment]
Not finding the port will happen the first time, or every time if you did not install the drivers.

**Comment by Cbo11** [comment]
how do i install the drivers properly, ive been trying to:
open the mtkdrivers.exe
unplug my phone
and than reboot my pc. i dont know why, but i dont think the drivers are installing?

**Comment by Cbo11** [comment]
my phone is the tcl flip pro if that helps any?

**Comment by neutronscott** [comment]
Sorry that's a different phone. This is not for you

**Comment by neutronscott** [comment]
flip pro isn't mediatek

**Comment by ys770** [comment]
i had an issue with my computer and had ended up installing the MTK drivers. i tried reinstalling but the auto booter gives the error that "NO MTK PRELOADER PORTS FOUND" how do i fix this?
