### ISSUE TITLE
Small suggestions to show progress

### ISSUE THREAD

**Issue by lionscribe** [neutronscott/flip2#2]
You can add the -p option to the push, so that it shows progress
`adb push -p super.bin /dev/block/mmcblk0p41`

Also, for correct Security (not sure if needed), it would be correct to reset the permissions when done, as follows;
`adb shell su -c chmod a-rw /dev/block/mmcblk0p41`

Thank you for all the work. I wrote for myself a simple batch file using your commands, and it literally takes me minutes to flash.

**Comment by lgexalter** [comment]
> You can add the -p option to the push, so that it shows progress `adb push -p super.bin /dev/block/mmcblk0p41`
> 
> Also, for correct Security (not sure if needed), it would be correct to reset the permissions when done, as follows; `adb shell su -c chmod a-rw /dev/block/mmcblk0p41`
> 
> Thank you for all the work. I wrote for myself a simple batch file using your commands, and it literally takes me minutes to flash.

Are you sure you should be removing rw for all users? Wouldn't that cause super not to be read at all and not boot? (That is if setting permissions in recovery is at all permanent. If it isn't then no need to change back permissions regardless....)

**Comment by neutronscott** [comment]
I edited the wiki to add `-p` but the chmod doesn't persist and I'd think you'd reboot after that.
