### ISSUE TITLE
Can't install APKs

### ISSUE THREAD

**Issue by Thomario20** [neutronscott/flip2#22]
Tried many reboots and resetting phone/reflashing boot image and i still can't get apps to install from the browser nor adb
Here is adb's error
![20240714_212514](https://github.com/user-attachments/assets/4ebae6da-c191-4232-87dd-5a6f6c3da00c)
And the phone just sais app not installed

**Comment by Thomario20** [comment]
Also note that it worked the first time I did it (but only for 1 boot)

**Comment by Thomario20** [comment]
Alright so apparently I can install some apps but not some other apps (I couldn't install zarchiver and roblox from the playstore app but I could install roblox from softonic) yes roblox. Was my first thing that came up ik my head

**Comment by neutronscott** [comment]
Can't find native library makes me think it only is arm64. Most devices are. This phone is only 32 bit

**Comment by Thomario20** [comment]
That would.. actually make a lot of sense. Why make a phone that you can't do anything (normally) arm64. Would that count as resolved at this point or something now?

**Comment by neutronscott** [comment]
Yeah it's best I can answer. Hopefully the application has another APK available for universal or armeabi-v7a CPU targets.

**Comment by Thomario20** [comment]
Yea I'll see if I can find a version supported for the apps I wanted to get on there. Thanks for the help anyway
