### ISSUE TITLE
Fastboot Flash Userdata?

### ISSUE THREAD

**Issue by levone1** [neutronscott/flip2#25]
@HSBERG @neutronscott (or anyone...) - wondering if any insight here.

I have a backup Flip2, and I had the thought to dd my userdata (mmcblk0p43), and flash it to other phone.  img flashes normally, without error, but never boots.  It only gets as far as TCL logo for about 2 seconds, and then goes to recovery, with a message about data corruption.

Tried a few ways, in regards to what state the backup phone is in when flashing userdata - clean wipe, root with write_protect 0, with and without vbmeta bins, etc., and always the same.  I wondered if maybe related to config/settings-type-stuff, but not sure where that info would be, if not in userdata, since super is never touched...  Maybe lk, or dtbo, or...?  I don't really know what those partitions are.

For example, on my current phone, I have adoptable storage set up, with app data on sd card - would that cause a problem if the other phone is not set up that way first?  Etc...

I have flashed a userdata img before to the same Flip2 that it came off of, and there were a few settings issues, like I had to re-modify resolution, etc., but it booted, and seemed fine overall.  Is there an issue with serial # or other identifiers stored in the userdata that don't match on the new phone?

Thanks

**Comment by neutronscott** [comment]
Pretty sure it's encrypted with data unique to the phone

**Comment by levone1** [comment]
> Pretty sure it's encrypted with data unique to the phone

Ok, thanks...  Maybe I'll at least try an adb backup
