### ISSUE TITLE
Update Magisk

### ISSUE THREAD

**Issue by alanzhao** [neutronscott/flip2#34]
How can we update magisk app to 28.1?  Looks like the direct install fails with a message

```
/dev/block/mmcblk0p33 is read only
```

Do we need a new patched boot.img and flash via fastboot? Ty!

**Comment by mmare155** [comment]
Im also experiencing the same issue. Could someone please help resolve

**Comment by neutronscott** [comment]
Typically you adb push the neutron.img to the phone /sdcard or such, patch it, bring back to PC, and use fastboot again to flash.

**Comment by mmare155** [comment]
to what file do I patch it, I know nothing about coding I'm simply following the instructions from flip2 guide

**Comment by alanzhao** [comment]
https://topjohnwu.github.io/Magisk/install.html @mmare155  you can follow that guide for how to patch the boot img, make sure you do not patch it as recovery, it's boot.img.

Gist: 
1. upload latest neutron.img to sd
2. patch the img file with magisk app (follow the link for how)
3.  adb pull down your newly patched img
4. put phone into fastboot mode (follow main guide)
5. fastboot flash your new img
6. restart and update magisk, and restart again.
