### ISSUE TITLE
neutron.img flashes but I cannot see magisk stub or full installed??

### ISSUE THREAD

**Issue by mitchellurgero** [neutronscott/flip2#4]
Should I be expecting magisk to install with the boot image in your wiki? I followed the instructions as shown but something isn't working right - also no errors to speak of.

Unlock worked, flashing boot returned OK but cannot install apks and cannot find magisk. Any tips from anyone that has used this guide?

**Comment by mitchellurgero** [comment]
OK So I think I fixed this by also flashing the vbameta files from apps4flip

**Comment by neutronscott** [comment]
Likely just rebooting fix this. There seems to be a timing issue when starting magisk.

**Comment by mitchellurgero** [comment]
Thanks for the response! I was reading through apps4flip and that does indeed seem to be the case as other users have seen as well. Flashing vbmeta is probably still not a bad idea if you're running certain modules, but not needed for root so case closed!

Thanks again!
