### ISSUE TITLE
MTK META Utility

### ISSUE THREAD

**Issue by dav473programer** [neutronscott/flip2#9]
I have observed that MTK META Utility doesn't work saying it needs an update(i downloaded even the latest version which is said to be v122).Has anyone got a patched version or some kind of version that doesn't say this?
![Screenshot 2023-12-04 163006](https://github.com/neutronscott/flip2/assets/136991184/f202ec44-923e-4bef-966a-3b6479dd99cb)
![Screenshot 2023-12-04 163129](https://github.com/neutronscott/flip2/assets/136991184/6093e4f2-6b79-461f-9a56-cdedc5e16298)

**Comment by dav473programer** [comment]
The owner changed some things and now his account is this:
https://www.facebook.com/mfdl.io
The download link to the new MTK META is now named android utility and the download is here:
https://www.facebook.com/mfdl.io

**Comment by dav473programer** [comment]
I tried that but gave me the same error as in the above error message.seems like v124 works for me.

**Comment by HSBERG** [comment]
@levone1 If you wouldn't mind sharing, I would put it in [my repo](https://github.com/HSBERG/TCL-FLIP-2-GUIDE) where i'm writing a more precise and direct tutorial. I would love to document it. Thanks!

**Comment by levone1** [comment]
Here's a Python script from @neutronscott and an autobooter.py that I've been using.  Sorry, can't remember exactly where it came from... So many threads/links

autobooter.py -  https://mega.nz/file/lkdx2QZI#CIsV1-MhfuSzwXR75V08SYP0usNNBojxFE2S8JhB0Fg
fastboot Python script - https://mega.nz/file/ks8RWBiL#9nNd6EjTtn0f4nyCM8tYRM21Zephlt1spaGy-XJMFy4

Besides that I have a couple of MTKMetaUtility versions that I think I've used for something here and there, but you can probably find.  Thanks for keeping it up

**Comment by levone1** [comment]
@HSBERG - Do you happen to have stock boot.img?

**Comment by FoxyDrew** [comment]
> @HSBERG - Do you happen to have stock boot.img?
> 
> -- NVM - I just remembered I have the stock fw file...

Where did you get the stock fw file?

Can I have a copy?

**Comment by levone1** [comment]
> > @HSBERG - Do you happen to have stock boot.img?
> > -- NVM - I just remembered I have the stock fw file...
> 
> Where did you get the stock fw file?
> 
> Can I have a copy?

Sorry - I honestly can't remember where I got it.  I will upload it somewhere and post a link, (if ok here - I'm not sure if it's technically something you're not "supposed to" share; I noticed that all of the super.img files that were posted on A4F and elsewhere seem to have disappeared; someone can let me know...).  I also do have stock super.img, if ok to share

**Comment by levone1** [comment]
> > @HSBERG - Do you happen to have stock boot.img?
> > -- NVM - I just remembered I have the stock fw file...
> 
> Where did you get the stock fw file?
> 
> Can I have a copy?

https://mega.nz/file/Q0cRnC7S#GKHA1zUIn_EGUvVCnL-pBTWlIzoYzNP1_83T1StVJh8

**Comment by levone1** [comment]
> @levone1 If you wouldn't mind sharing, I would put it in [my repo](https://github.com/HSBERG/TCL-FLIP-2-GUIDE) where i'm writing a more precise and direct tutorial. I would love to document it. Thanks!

Have you see this - https://github.com/twrpdtgen/android_device_tcl_Gflip6_TF/tree/full_gflip6tf-user-11-RP1A.200720.011-KEEZ-release-keys ?

I tried merging and building, but get error at the last step, "ckati failed with: exit status 1".  I see several reports of that error, but usually says it's a low memory problem.  I'm running 32gb ram, so don't think so in my case

**Comment by Synchr0zine** [comment]
> > > @HSBERG - Do you happen to have stock boot.img?
> > > -- NVM - I just remembered I have the stock fw file...
> > 
> > 
> > Where did you get the stock fw file?
> > Can I have a copy?
> 
> https://mega.nz/file/Q0cRnC7S#GKHA1zUIn_EGUvVCnL-pBTWlIzoYzNP1_83T1StVJh8

can I ask how do you flash this file to the device?

**Comment by levone1** [comment]
> > > > @HSBERG - Do you happen to have stock boot.img?
> > > > -- NVM - I just remembered I have the stock fw file...
> > > 
> > > 
> > > Where did you get the stock fw file?
> > > Can I have a copy?
> > 
> > 
> > https://mega.nz/file/Q0cRnC7S#GKHA1zUIn_EGUvVCnL-pBTWlIzoYzNP1_83T1StVJh8
> 
> can I ask how do you flash this file to the device?

I haven't done a full stock fw flash on Flip2.  I guess you should technically be able to use MTKMeta, but not sure.  There is a flash script in the file, (follow the META-INF folder path), which shows how it gets flashed, but probably need some good understanding to follow it, and deal with any errors, etc...

If you want to restore to stock, the easiest thing is to get a super.img, (which I guess you could make from the fw file if you know what you're doing), and fastboot it.  I can post it if you need

**Comment by Synchr0zine** [comment]
> > > > > @HSBERG - Do you happen to have stock boot.img?
> > > > > -- NVM - I just remembered I have the stock fw file...
> > > > 
> > > > 
> > > > Where did you get the stock fw file?
> > > > Can I have a copy?
> > > 
> > > 
> > > https://mega.nz/file/Q0cRnC7S#GKHA1zUIn_EGUvVCnL-pBTWlIzoYzNP1_83T1StVJh8
> > 
> > 
> > can I ask how do you flash this file to the device?
> 
> I haven't done a full stock fw flash on Flip2. I guess you should technically be able to use MTKMeta, but not sure. There is a flash script in the file, (follow the META-INF folder path), which shows how it gets flashed, but probably need some good understanding to follow it, and deal with any errors, etc...
> 
> If you want to restore to stock, the easiest thing is to get a super.img, (which I guess you could make from the fw file if you know what you're doing), and fastboot it. I can post it if you need, or, if you have a booted phone, dump your own super - 'dd if=/dev/block/mmcblk0p41 of=/wherever/you/want/super.img'... (double check p41; I think that's what it was). It's a big file, (+2gb)

I would really appreciate if you could post the stock super. I have been trying to find it for ages

**Comment by levone1** [comment]
> > > > > > @HSBERG - Do you happen to have stock boot.img?
> > > > > > -- NVM - I just remembered I have the stock fw file...
> > > > > 
> > > > > 
> > > > > Where did you get the stock fw file?
> > > > > Can I have a copy?
> > > > 
> > > > 
> > > > https://mega.nz/file/Q0cRnC7S#GKHA1zUIn_EGUvVCnL-pBTWlIzoYzNP1_83T1StVJh8
> > > 
> > > 
> > > can I ask how do you flash this file to the device?
> > 
> > 
> > I haven't done a full stock fw flash on Flip2. I guess you should technically be able to use MTKMeta, but not sure. There is a flash script in the file, (follow the META-INF folder path), which shows how it gets flashed, but probably need some good understanding to follow it, and deal with any errors, etc...
> > If you want to restore to stock, the easiest thing is to get a super.img, (which I guess you could make from the fw file if you know what you're doing), and fastboot it. I can post it if you need, or, if you have a booted phone, dump your own super - 'dd if=/dev/block/mmcblk0p41 of=/wherever/you/want/super.img'... (double check p41; I think that's what it was). It's a big file, (+2gb)
> 
> I would really appreciate if you could post the stock super. I have been trying to find it for ages

https://mega.nz/file/R9dj1IwL#7unxGc2eR2DjDjTsZDjFBPNm302OAeJrbpnw42mezWI

**Comment by neutronscott** [comment]
wiki updated to use autobooter
